# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - init: |-
      ./.gitpod/setup.sh
  - init: |-
      echo 'init script'; # runs during prebuild
      npm install;
      npm run build;
    command: echo 'start script'

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
#ports:
#  - port: 3000
#    onOpen: open-preview
