# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - name: Front End Dev Server
    before: |-
      npm install -g @angular/cli
    init: |-
      cd src/DateNightRandomizerWeb;
      npm install;
    command: |-
      cd src/DateNightRandomizerWeb;
      ng serve
  - name: App Server
    init: |-
      echo 'init script'; # runs during prebuild
      cd src/DateNightRandomizerConsole;
      npm install;
      npm run build;
    command: |-
      echo 'start script'
      ./.gitpod/setup.sh;
      cd src/DateNightRandomizerConsole;

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 4200
    onOpen: open-preview

github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    pullRequestsFromForks: false
    addComment: false
    addBadge: true

